"""
LLM ツール名のプレフィックスとツール名定数。

ツール名は「カテゴリプレフィックス_機能名」の形式とし、
利用可能ツール一覧でカテゴリが分かるようにする。
"""

from typing import List, Tuple

# --- プレフィックス一覧（カテゴリ） ---
TOOL_NAME_PREFIX_WORLD = "world_"
TOOL_NAME_PREFIX_MOVE = "move_"
TOOL_NAME_PREFIX_SPEECH = "speech_"
TOOL_NAME_PREFIX_HARVEST = "harvest_"
TOOL_NAME_PREFIX_CONVERSATION = "conversation_"
TOOL_NAME_PREFIX_COMBAT = "combat_"
TOOL_NAME_PREFIX_SKILL = "skill_"
TOOL_NAME_PREFIX_QUEST = "quest_"
TOOL_NAME_PREFIX_GUILD = "guild_"
TOOL_NAME_PREFIX_SHOP = "shop_"
TOOL_NAME_PREFIX_TRADE = "trade_"
TOOL_NAME_PREFIX_SNS = "sns_"
TOOL_NAME_PREFIX_TODO = "todo_"
TOOL_NAME_PREFIX_MEMO = "memo_"
TOOL_NAME_PREFIX_MEMORY = "memory_"
# PR-CC (Y_after_pr639_640 後続): spot_graph_ prefix を廃止し、bare 名で
# 露出する。理由:
# - LLM は spot_graph mode / tile_map mode 排他なので、mode ごとに露出する
#   tool set が既に決まっている。prefix で「これは spot_graph 系」と分ける
#   必要がない
# - LLM prompt に 13 tools × ~10 char prefix = ~130 char/prompt を毎回
#   注ぎ込んでいた無駄を削減 (勘定は tool_names 配列文字列)
# - "harvest" のような hallucinate 誤発明も抑制できる
# Python の定数名 (TOOL_NAME_SPOT_GRAPH_* / TOOL_NAME_PREFIX_SPOT_GRAPH)
# は grep 継続性のため据え置く。値だけ空文字にする。
TOOL_NAME_PREFIX_SPOT_GRAPH = ""

# プレフィックス一覧（ドキュメント・バリデーション用）。順序は表示に影響しない。
TOOL_NAME_PREFIXES: List[str] = [
    TOOL_NAME_PREFIX_WORLD,
    TOOL_NAME_PREFIX_MOVE,
    TOOL_NAME_PREFIX_SPEECH,
    TOOL_NAME_PREFIX_HARVEST,
    TOOL_NAME_PREFIX_CONVERSATION,
    TOOL_NAME_PREFIX_COMBAT,
    TOOL_NAME_PREFIX_SKILL,
    TOOL_NAME_PREFIX_QUEST,
    TOOL_NAME_PREFIX_GUILD,
    TOOL_NAME_PREFIX_SHOP,
    TOOL_NAME_PREFIX_TRADE,
    TOOL_NAME_PREFIX_SNS,
]

# プレフィックスと説明の対応（ドキュメント用）
TOOL_NAME_PREFIX_DESCRIPTIONS: List[Tuple[str, str]] = [
    (TOOL_NAME_PREFIX_WORLD, "ワールド・ゲーム全体"),
    (TOOL_NAME_PREFIX_MOVE, "移動"),
    (TOOL_NAME_PREFIX_SPEECH, "会話・発言"),
    (TOOL_NAME_PREFIX_HARVEST, "採集"),
    (TOOL_NAME_PREFIX_CONVERSATION, "会話進行"),
    (TOOL_NAME_PREFIX_COMBAT, "戦闘"),
    (TOOL_NAME_PREFIX_SKILL, "スキル管理"),
    (TOOL_NAME_PREFIX_QUEST, "クエスト"),
    (TOOL_NAME_PREFIX_GUILD, "ギルド"),
    (TOOL_NAME_PREFIX_SHOP, "ショップ"),
    (TOOL_NAME_PREFIX_TRADE, "取引"),
    (TOOL_NAME_PREFIX_SNS, "SNS"),
]

# --- ツール名（プレフィックス付き） ---
TOOL_NAME_NO_OP = TOOL_NAME_PREFIX_WORLD + "no_op"
TOOL_NAME_INSPECT_ITEM = TOOL_NAME_PREFIX_WORLD + "inspect_item"
TOOL_NAME_INSPECT_TARGET = TOOL_NAME_PREFIX_WORLD + "inspect_target"
TOOL_NAME_INTERACT_WORLD_OBJECT = TOOL_NAME_PREFIX_WORLD + "interact"
TOOL_NAME_CHANGE_ATTENTION = TOOL_NAME_PREFIX_WORLD + "change_attention"
TOOL_NAME_PLACE_OBJECT = TOOL_NAME_PREFIX_WORLD + "place_object"
TOOL_NAME_DESTROY_PLACEABLE = TOOL_NAME_PREFIX_WORLD + "destroy_placeable"
TOOL_NAME_DROP_ITEM = TOOL_NAME_PREFIX_WORLD + "drop_item"
TOOL_NAME_PURSUIT_START = TOOL_NAME_PREFIX_WORLD + "pursue_target"
TOOL_NAME_PURSUIT_CANCEL = TOOL_NAME_PREFIX_WORLD + "cancel_pursuit"
# 移動は 1 ツール（set_destination と tick_movement を分けない）。内部で SetDestinationCommand を使用。
TOOL_NAME_MOVE_TO_DESTINATION = TOOL_NAME_PREFIX_MOVE + "to_destination"
TOOL_NAME_MOVE_ONE_STEP = TOOL_NAME_PREFIX_MOVE + "one_step"
TOOL_NAME_CANCEL_MOVEMENT = TOOL_NAME_PREFIX_MOVE + "cancel"
# Issue #264 後続: 旧 SAY/WHISPER の 2 tool を廃止し、``channel`` 引数を持つ
# 単一 ``speech_speak`` tool に統合した (SHOUT も同時に LLM へ公開)。
# ``channel`` は arguments で "whisper" / "say" / "shout" のいずれかを指定する。
# 詳細は tool_catalog/spot_graph.py の SPEECH_DEFINITION を参照。
TOOL_NAME_SPEECH = TOOL_NAME_PREFIX_SPEECH + "speak"
TOOL_NAME_HARVEST_START = TOOL_NAME_PREFIX_HARVEST + "start"
TOOL_NAME_HARVEST_CANCEL = TOOL_NAME_PREFIX_HARVEST + "cancel"
TOOL_NAME_CONVERSATION_ADVANCE = TOOL_NAME_PREFIX_CONVERSATION + "advance"
TOOL_NAME_CHEST_STORE = TOOL_NAME_PREFIX_WORLD + "chest_store"
TOOL_NAME_CHEST_TAKE = TOOL_NAME_PREFIX_WORLD + "chest_take"
TOOL_NAME_COMBAT_USE_SKILL = TOOL_NAME_PREFIX_COMBAT + "use_skill"
TOOL_NAME_SKILL_EQUIP = TOOL_NAME_PREFIX_SKILL + "equip"
TOOL_NAME_SKILL_ACCEPT_PROPOSAL = TOOL_NAME_PREFIX_SKILL + "accept_proposal"
TOOL_NAME_SKILL_REJECT_PROPOSAL = TOOL_NAME_PREFIX_SKILL + "reject_proposal"
TOOL_NAME_SKILL_ACTIVATE_AWAKENED_MODE = TOOL_NAME_PREFIX_SKILL + "activate_awakened_mode"
TOOL_NAME_QUEST_ACCEPT = TOOL_NAME_PREFIX_QUEST + "accept"
TOOL_NAME_QUEST_CANCEL = TOOL_NAME_PREFIX_QUEST + "cancel"
TOOL_NAME_QUEST_APPROVE = TOOL_NAME_PREFIX_QUEST + "approve"
TOOL_NAME_QUEST_ISSUE = TOOL_NAME_PREFIX_QUEST + "issue"
TOOL_NAME_GUILD_CREATE = TOOL_NAME_PREFIX_GUILD + "create"
TOOL_NAME_GUILD_ADD_MEMBER = TOOL_NAME_PREFIX_GUILD + "add_member"
TOOL_NAME_GUILD_CHANGE_ROLE = TOOL_NAME_PREFIX_GUILD + "change_role"
TOOL_NAME_GUILD_DISBAND = TOOL_NAME_PREFIX_GUILD + "disband"
TOOL_NAME_GUILD_LEAVE = TOOL_NAME_PREFIX_GUILD + "leave"
TOOL_NAME_GUILD_DEPOSIT_BANK = TOOL_NAME_PREFIX_GUILD + "deposit_bank"
TOOL_NAME_GUILD_WITHDRAW_BANK = TOOL_NAME_PREFIX_GUILD + "withdraw_bank"
TOOL_NAME_SHOP_PURCHASE = TOOL_NAME_PREFIX_SHOP + "purchase"
TOOL_NAME_SHOP_LIST_ITEM = TOOL_NAME_PREFIX_SHOP + "list_item"
TOOL_NAME_SHOP_UNLIST_ITEM = TOOL_NAME_PREFIX_SHOP + "unlist_item"
TOOL_NAME_TRADE_ENTER = TOOL_NAME_PREFIX_TRADE + "enter"
TOOL_NAME_TRADE_EXIT = TOOL_NAME_PREFIX_TRADE + "exit"
TOOL_NAME_TRADE_OFFER = TOOL_NAME_PREFIX_TRADE + "offer"
TOOL_NAME_TRADE_ACCEPT = TOOL_NAME_PREFIX_TRADE + "accept"
TOOL_NAME_TRADE_CANCEL = TOOL_NAME_PREFIX_TRADE + "cancel"
TOOL_NAME_TRADE_DECLINE = TOOL_NAME_PREFIX_TRADE + "decline"
TOOL_NAME_TRADE_VIEW_CURRENT_PAGE = TOOL_NAME_PREFIX_TRADE + "view_current_page"
TOOL_NAME_TRADE_OPEN_PAGE = TOOL_NAME_PREFIX_TRADE + "open_page"
TOOL_NAME_TRADE_PAGE_NEXT = TOOL_NAME_PREFIX_TRADE + "page_next"
TOOL_NAME_TRADE_PAGE_REFRESH = TOOL_NAME_PREFIX_TRADE + "page_refresh"
TOOL_NAME_TRADE_SWITCH_TAB = TOOL_NAME_PREFIX_TRADE + "switch_tab"
TOOL_NAME_SNS_CREATE_POST = TOOL_NAME_PREFIX_SNS + "create_post"
TOOL_NAME_SNS_CREATE_REPLY = TOOL_NAME_PREFIX_SNS + "create_reply"
TOOL_NAME_SNS_LIKE_POST = TOOL_NAME_PREFIX_SNS + "like_post"
TOOL_NAME_SNS_LIKE_REPLY = TOOL_NAME_PREFIX_SNS + "like_reply"
TOOL_NAME_SNS_FOLLOW = TOOL_NAME_PREFIX_SNS + "follow"
TOOL_NAME_SNS_UNFOLLOW = TOOL_NAME_PREFIX_SNS + "unfollow"
TOOL_NAME_SNS_SUBSCRIBE = TOOL_NAME_PREFIX_SNS + "subscribe"
TOOL_NAME_SNS_UNSUBSCRIBE = TOOL_NAME_PREFIX_SNS + "unsubscribe"
TOOL_NAME_SNS_BLOCK = TOOL_NAME_PREFIX_SNS + "block"
TOOL_NAME_SNS_UNBLOCK = TOOL_NAME_PREFIX_SNS + "unblock"
TOOL_NAME_SNS_ENTER = TOOL_NAME_PREFIX_SNS + "enter"
TOOL_NAME_SNS_LOGOUT = TOOL_NAME_PREFIX_SNS + "logout"
TOOL_NAME_SNS_DELETE_POST = TOOL_NAME_PREFIX_SNS + "delete_post"
TOOL_NAME_SNS_DELETE_REPLY = TOOL_NAME_PREFIX_SNS + "delete_reply"
TOOL_NAME_SNS_UPDATE_PROFILE = TOOL_NAME_PREFIX_SNS + "update_profile"
TOOL_NAME_SNS_MARK_NOTIFICATION_READ = TOOL_NAME_PREFIX_SNS + "mark_notification_read"
TOOL_NAME_SNS_MARK_ALL_NOTIFICATIONS_READ = TOOL_NAME_PREFIX_SNS + "mark_all_notifications_read"
TOOL_NAME_SNS_VIEW_CURRENT_PAGE = TOOL_NAME_PREFIX_SNS + "view_current_page"
TOOL_NAME_SNS_OPEN_PAGE = TOOL_NAME_PREFIX_SNS + "open_page"
TOOL_NAME_SNS_OPEN_REF = TOOL_NAME_PREFIX_SNS + "open_ref"
TOOL_NAME_SNS_PAGE_NEXT = TOOL_NAME_PREFIX_SNS + "page_next"
TOOL_NAME_SNS_PAGE_REFRESH = TOOL_NAME_PREFIX_SNS + "page_refresh"
TOOL_NAME_SNS_SWITCH_TAB = TOOL_NAME_PREFIX_SNS + "switch_tab"
TOOL_NAME_MEMO_ADD = TOOL_NAME_PREFIX_MEMO + "add"
TOOL_NAME_MEMO_LIST = TOOL_NAME_PREFIX_MEMO + "list"
TOOL_NAME_MEMO_DONE = TOOL_NAME_PREFIX_MEMO + "done"
# 後方互換のため旧 TODO 名を memo へのエイリアスとして残す (Issue #188 リネーム)。
# 既存テスト / docstring の参照を一気に直さなくて済むようにする。
# 新規コードは TOOL_NAME_MEMO_* を使うこと。
TOOL_NAME_TODO_ADD = TOOL_NAME_MEMO_ADD
TOOL_NAME_TODO_LIST = TOOL_NAME_MEMO_LIST
TOOL_NAME_TODO_COMPLETE = TOOL_NAME_MEMO_DONE
TOOL_NAME_MEMORY_EXPLORE_RELATED = TOOL_NAME_PREFIX_MEMORY + "explore_related"
TOOL_NAME_MEMORY_SEARCH_SEMANTIC = TOOL_NAME_PREFIX_MEMORY + "search_semantic"
# Issue #526 後続: episodic memory の能動 recall ツール (= 「思い出そう」と
# 意志して過去 episode を取り戻す経路)。passive recall は prompt 構築で
# 自動で走るが、この tool は LLM が ``about`` + ``time_range`` を渡して
# 能動的に過去を呼び戻す。
TOOL_NAME_MEMORY_RECALL_EPISODES = TOOL_NAME_PREFIX_MEMORY + "recall_episodes"
# Issue #526 後続 PR-D: afterglow index (= ぼんやり覚えてる見出し) から、
# 「これ詳しく思い出したい」と handle を指定して本文を引き戻す経路。
# memory_recall_episodes が自由文検索なのに対し、これは prompt 上の handle
# (``ep_<6 文字>``) を直接指定して 1 件取り出す。slot に再注入されるため
# 「もう一度鮮明に浮かんだ」状態を構造で実現する。
TOOL_NAME_MEMORY_RECALL_BY_HANDLE = TOOL_NAME_PREFIX_MEMORY + "recall_by_handle"
TOOL_NAME_SPOT_GRAPH_TRAVEL_TO = TOOL_NAME_PREFIX_SPOT_GRAPH + "travel_to"
TOOL_NAME_SPOT_GRAPH_SET_SUB_LOCATION = TOOL_NAME_PREFIX_SPOT_GRAPH + "set_sub_location"
TOOL_NAME_SPOT_GRAPH_EXPLORE = TOOL_NAME_PREFIX_SPOT_GRAPH + "explore"
TOOL_NAME_SPOT_GRAPH_INTERACT = TOOL_NAME_PREFIX_SPOT_GRAPH + "interact"
TOOL_NAME_SPOT_GRAPH_WAIT = TOOL_NAME_PREFIX_SPOT_GRAPH + "wait"
TOOL_NAME_SPOT_GRAPH_PREPARE_ACTION = TOOL_NAME_PREFIX_SPOT_GRAPH + "prepare_action"
TOOL_NAME_SPOT_GRAPH_USE_ITEM = TOOL_NAME_PREFIX_SPOT_GRAPH + "use_item"
TOOL_NAME_SPOT_GRAPH_ATTACK = TOOL_NAME_PREFIX_SPOT_GRAPH + "attack"
TOOL_NAME_SPOT_GRAPH_LISTEN = TOOL_NAME_PREFIX_SPOT_GRAPH + "listen"
TOOL_NAME_SPOT_GRAPH_DROP_ITEM = TOOL_NAME_PREFIX_SPOT_GRAPH + "drop_item"
TOOL_NAME_SPOT_GRAPH_PICKUP_ITEM = TOOL_NAME_PREFIX_SPOT_GRAPH + "pickup_item"
TOOL_NAME_SPOT_GRAPH_GIVE_ITEM = TOOL_NAME_PREFIX_SPOT_GRAPH + "give_item"
# PR 5b: 同 tick 内で複数 give を 1 tool call にまとめるための batch 版。
# 単発 give_item は受け渡しが 1 対 1 のとき / 引数を最小化したいとき向けに残す。
TOOL_NAME_SPOT_GRAPH_GIVE_ITEMS = TOOL_NAME_PREFIX_SPOT_GRAPH + "give_items"
# Issue #621 Phase 3b: 同 spot に倒れた仲間を介抱して revive する tool。
# アイテム (= first_aid) を持っていなくても物理的に起こす経路。
TOOL_NAME_SPOT_GRAPH_TEND_TO_PLAYER = TOOL_NAME_PREFIX_SPOT_GRAPH + "tend_to_player"
