"""
LLM ツール名のプレフィックスとツール名定数。

ツール名は「カテゴリプレフィックス_機能名」の形式とし、
利用可能ツール一覧でカテゴリが分かるようにする。
"""

from typing import List, Tuple

# --- プレフィックス一覧（カテゴリ） ---
TOOL_NAME_PREFIX_WORLD = "world_"
TOOL_NAME_PREFIX_MOVE = "move_"
TOOL_NAME_PREFIX_SPEECH = "speech_"
TOOL_NAME_PREFIX_HARVEST = "harvest_"
TOOL_NAME_PREFIX_CONVERSATION = "conversation_"
TOOL_NAME_PREFIX_COMBAT = "combat_"
TOOL_NAME_PREFIX_SKILL = "skill_"
TOOL_NAME_PREFIX_QUEST = "quest_"
TOOL_NAME_PREFIX_GUILD = "guild_"
TOOL_NAME_PREFIX_SHOP = "shop_"
TOOL_NAME_PREFIX_TRADE = "trade_"
TOOL_NAME_PREFIX_SNS = "sns_"
TOOL_NAME_PREFIX_MEMORY = "memory_"
TOOL_NAME_PREFIX_TODO = "todo_"

# プレフィックス一覧（ドキュメント・バリデーション用）。順序は表示に影響しない。
TOOL_NAME_PREFIXES: List[str] = [
    TOOL_NAME_PREFIX_WORLD,
    TOOL_NAME_PREFIX_MOVE,
    TOOL_NAME_PREFIX_SPEECH,
    TOOL_NAME_PREFIX_HARVEST,
    TOOL_NAME_PREFIX_CONVERSATION,
    TOOL_NAME_PREFIX_COMBAT,
    TOOL_NAME_PREFIX_SKILL,
    TOOL_NAME_PREFIX_QUEST,
    TOOL_NAME_PREFIX_GUILD,
    TOOL_NAME_PREFIX_SHOP,
    TOOL_NAME_PREFIX_TRADE,
    TOOL_NAME_PREFIX_SNS,
]

# プレフィックスと説明の対応（ドキュメント用）
TOOL_NAME_PREFIX_DESCRIPTIONS: List[Tuple[str, str]] = [
    (TOOL_NAME_PREFIX_WORLD, "ワールド・ゲーム全体"),
    (TOOL_NAME_PREFIX_MOVE, "移動"),
    (TOOL_NAME_PREFIX_SPEECH, "会話・発言"),
    (TOOL_NAME_PREFIX_HARVEST, "採集"),
    (TOOL_NAME_PREFIX_CONVERSATION, "会話進行"),
    (TOOL_NAME_PREFIX_COMBAT, "戦闘"),
    (TOOL_NAME_PREFIX_SKILL, "スキル管理"),
    (TOOL_NAME_PREFIX_QUEST, "クエスト"),
    (TOOL_NAME_PREFIX_GUILD, "ギルド"),
    (TOOL_NAME_PREFIX_SHOP, "ショップ"),
    (TOOL_NAME_PREFIX_TRADE, "取引"),
    (TOOL_NAME_PREFIX_SNS, "SNS"),
]

# --- ツール名（プレフィックス付き） ---
TOOL_NAME_NO_OP = TOOL_NAME_PREFIX_WORLD + "no_op"
TOOL_NAME_INSPECT_ITEM = TOOL_NAME_PREFIX_WORLD + "inspect_item"
TOOL_NAME_INSPECT_TARGET = TOOL_NAME_PREFIX_WORLD + "inspect_target"
TOOL_NAME_INTERACT_WORLD_OBJECT = TOOL_NAME_PREFIX_WORLD + "interact"
TOOL_NAME_CHANGE_ATTENTION = TOOL_NAME_PREFIX_WORLD + "change_attention"
TOOL_NAME_PLACE_OBJECT = TOOL_NAME_PREFIX_WORLD + "place_object"
TOOL_NAME_DESTROY_PLACEABLE = TOOL_NAME_PREFIX_WORLD + "destroy_placeable"
TOOL_NAME_DROP_ITEM = TOOL_NAME_PREFIX_WORLD + "drop_item"
TOOL_NAME_PURSUIT_START = TOOL_NAME_PREFIX_WORLD + "pursue_target"
TOOL_NAME_PURSUIT_CANCEL = TOOL_NAME_PREFIX_WORLD + "cancel_pursuit"
# 移動は 1 ツール（set_destination と tick_movement を分けない）。内部で SetDestinationCommand を使用。
TOOL_NAME_MOVE_TO_DESTINATION = TOOL_NAME_PREFIX_MOVE + "to_destination"
TOOL_NAME_MOVE_ONE_STEP = TOOL_NAME_PREFIX_MOVE + "one_step"
TOOL_NAME_CANCEL_MOVEMENT = TOOL_NAME_PREFIX_MOVE + "cancel"
TOOL_NAME_WHISPER = TOOL_NAME_PREFIX_SPEECH + "whisper"
TOOL_NAME_SAY = TOOL_NAME_PREFIX_SPEECH + "say"
TOOL_NAME_HARVEST_START = TOOL_NAME_PREFIX_HARVEST + "start"
TOOL_NAME_HARVEST_CANCEL = TOOL_NAME_PREFIX_HARVEST + "cancel"
TOOL_NAME_CONVERSATION_ADVANCE = TOOL_NAME_PREFIX_CONVERSATION + "advance"
TOOL_NAME_CHEST_STORE = TOOL_NAME_PREFIX_WORLD + "chest_store"
TOOL_NAME_CHEST_TAKE = TOOL_NAME_PREFIX_WORLD + "chest_take"
TOOL_NAME_COMBAT_USE_SKILL = TOOL_NAME_PREFIX_COMBAT + "use_skill"
TOOL_NAME_SKILL_EQUIP = TOOL_NAME_PREFIX_SKILL + "equip"
TOOL_NAME_SKILL_ACCEPT_PROPOSAL = TOOL_NAME_PREFIX_SKILL + "accept_proposal"
TOOL_NAME_SKILL_REJECT_PROPOSAL = TOOL_NAME_PREFIX_SKILL + "reject_proposal"
TOOL_NAME_SKILL_ACTIVATE_AWAKENED_MODE = TOOL_NAME_PREFIX_SKILL + "activate_awakened_mode"
TOOL_NAME_QUEST_ACCEPT = TOOL_NAME_PREFIX_QUEST + "accept"
TOOL_NAME_QUEST_CANCEL = TOOL_NAME_PREFIX_QUEST + "cancel"
TOOL_NAME_QUEST_APPROVE = TOOL_NAME_PREFIX_QUEST + "approve"
TOOL_NAME_QUEST_ISSUE = TOOL_NAME_PREFIX_QUEST + "issue"
TOOL_NAME_GUILD_CREATE = TOOL_NAME_PREFIX_GUILD + "create"
TOOL_NAME_GUILD_ADD_MEMBER = TOOL_NAME_PREFIX_GUILD + "add_member"
TOOL_NAME_GUILD_CHANGE_ROLE = TOOL_NAME_PREFIX_GUILD + "change_role"
TOOL_NAME_GUILD_DISBAND = TOOL_NAME_PREFIX_GUILD + "disband"
TOOL_NAME_GUILD_LEAVE = TOOL_NAME_PREFIX_GUILD + "leave"
TOOL_NAME_GUILD_DEPOSIT_BANK = TOOL_NAME_PREFIX_GUILD + "deposit_bank"
TOOL_NAME_GUILD_WITHDRAW_BANK = TOOL_NAME_PREFIX_GUILD + "withdraw_bank"
TOOL_NAME_SHOP_PURCHASE = TOOL_NAME_PREFIX_SHOP + "purchase"
TOOL_NAME_SHOP_LIST_ITEM = TOOL_NAME_PREFIX_SHOP + "list_item"
TOOL_NAME_SHOP_UNLIST_ITEM = TOOL_NAME_PREFIX_SHOP + "unlist_item"
TOOL_NAME_TRADE_OFFER = TOOL_NAME_PREFIX_TRADE + "offer"
TOOL_NAME_TRADE_ACCEPT = TOOL_NAME_PREFIX_TRADE + "accept"
TOOL_NAME_TRADE_CANCEL = TOOL_NAME_PREFIX_TRADE + "cancel"
TOOL_NAME_TRADE_DECLINE = TOOL_NAME_PREFIX_TRADE + "decline"
TOOL_NAME_SNS_CREATE_POST = TOOL_NAME_PREFIX_SNS + "create_post"
TOOL_NAME_SNS_CREATE_REPLY = TOOL_NAME_PREFIX_SNS + "create_reply"
TOOL_NAME_SNS_LIKE_POST = TOOL_NAME_PREFIX_SNS + "like_post"
TOOL_NAME_SNS_LIKE_REPLY = TOOL_NAME_PREFIX_SNS + "like_reply"
TOOL_NAME_SNS_FOLLOW = TOOL_NAME_PREFIX_SNS + "follow"
TOOL_NAME_SNS_UNFOLLOW = TOOL_NAME_PREFIX_SNS + "unfollow"
TOOL_NAME_SNS_SUBSCRIBE = TOOL_NAME_PREFIX_SNS + "subscribe"
TOOL_NAME_SNS_UNSUBSCRIBE = TOOL_NAME_PREFIX_SNS + "unsubscribe"
TOOL_NAME_SNS_BLOCK = TOOL_NAME_PREFIX_SNS + "block"
TOOL_NAME_SNS_UNBLOCK = TOOL_NAME_PREFIX_SNS + "unblock"
TOOL_NAME_MEMORY_QUERY = TOOL_NAME_PREFIX_MEMORY + "query"
TOOL_NAME_SUBAGENT = TOOL_NAME_PREFIX_MEMORY + "subagent"
TOOL_NAME_TODO_ADD = TOOL_NAME_PREFIX_TODO + "add"
TOOL_NAME_TODO_LIST = TOOL_NAME_PREFIX_TODO + "list"
TOOL_NAME_TODO_COMPLETE = TOOL_NAME_PREFIX_TODO + "complete"
TOOL_NAME_WORKING_MEMORY_APPEND = TOOL_NAME_PREFIX_MEMORY + "working_memory_append"
