"""dump に出る自動採番 id を、再生成しても変わらない別名へ畳む。

## なぜ要るか

`sem-…` / `belief-evidence-…` は生成地点で `uuid4()` を直接振っている。
seed で固定できず、テストから id を渡す口も無いので、`docs/quality_checks/`
の dump は**回すたびに差分が出る**。実際、この churn は経済統合の docs PR
(#1153) に紛れ込んで初めて見つかった。

## なぜ production に注入口を作らないか

人が読む dump のために本番へ seam を作ることになる。dump 側で畳めば済む話に
production の形を合わせない。

## なぜ id 行を消さずに畳むか

この dump で id が担っている意味は「同じ id が 2 か所に出る」という**参照の
一貫性**だけ (`entry_id` == `belief_id`、evidence が trace と buffer の両方に
出る)。生の uuid はそれ以上の情報を持たない。出現順の別名へ畳めば、一貫性は
読めるまま、文字列は毎回同じになる。
"""

from __future__ import annotations

import re
from typing import Dict

#: 畳む対象。接頭辞ごとに採番するので、`sem-#1` と `belief-evidence-#1` は
#: 別の系列になる。**32 桁の 16 進だけを対象にする**ので、テストが手で置いた
#: 安定 id (`sem-existing` など) は触らない。
_AUTOGENERATED_ID = re.compile(r"\b(sem|belief-evidence)-([0-9a-f]{32})\b")


class StableIdFolder:
    """同じ生 id には同じ別名を返す、出現順の採番器。"""

    def __init__(self) -> None:
        self._alias_by_raw: Dict[str, str] = {}
        self._count_by_prefix: Dict[str, int] = {}

    def fold(self, text: str) -> str:
        """text 中の自動採番 id を、出現順の別名へ置き換えた文字列を返す。"""
        return _AUTOGENERATED_ID.sub(self._alias_for_match, text)

    def _alias_for_match(self, match: "re.Match[str]") -> str:
        raw = match.group(0)
        known = self._alias_by_raw.get(raw)
        if known is not None:
            return known
        prefix = match.group(1)
        index = self._count_by_prefix.get(prefix, 0) + 1
        self._count_by_prefix[prefix] = index
        alias = f"{prefix}-#{index}"
        self._alias_by_raw[raw] = alias
        return alias


def fold_autogenerated_ids(text: str) -> str:
    """dump 全体を 1 度で畳む。

    **ファイル単位で 1 つの採番器を使う。** 節ごとに畳むと、同じ id が節を
    跨いだときに別の別名になり、参照の一貫性という唯一の値打ちが消える。
    """
    return StableIdFolder().fold(text)
