"""自動採番 id の畳み込みが、参照の一貫性を保ったまま安定するか。

畳み込み自体が壊れると、golden は「毎回同じだが意味が読めない」か「読めるが
毎回変わる」のどちらかに倒れる。dump を回すのは手動なので、壊れても気付く
のは次に誰かが再生成したときになる。ここで先に縛る。

このテストは quality マーカーを付けない。畳み込みは dump を回さなくても
検証できるので、通常の試験で見張る。
"""

from __future__ import annotations

from tests.quality._stable_ids import fold_autogenerated_ids

_A = "sem-8bce65a2475b4182a9e959543f0f761b"
_B = "sem-d0659d767b034ee4a9ba4729e9518c53"
_E = "belief-evidence-af2cc767e903444d9642767329d6dfaa"


class TestFoldingKeepsReferentialConsistency:
    """同じ id は同じ別名に、違う id は違う別名になる。"""

    def test_the_same_id_folds_to_the_same_alias_across_the_whole_dump(self) -> None:
        """離れた行に出る同じ id は、同じ別名になる (entry_id == belief_id が読める)。"""
        text = f"  entry_id: {_A}\n  belief_id: {_A}\n"

        assert fold_autogenerated_ids(text) == "  entry_id: sem-#1\n  belief_id: sem-#1\n"

    def test_different_ids_fold_to_different_aliases(self) -> None:
        """別の id は別の別名になる (2 件が同一に見えてしまわない)。"""
        folded = fold_autogenerated_ids(f"{_A} {_B}")

        assert folded == "sem-#1 sem-#2"

    def test_each_prefix_is_numbered_independently(self) -> None:
        """接頭辞ごとに採番する (sem と belief-evidence が同じ番号を共有しない)。"""
        folded = fold_autogenerated_ids(f"{_A} {_E}")

        assert folded == "sem-#1 belief-evidence-#1"

    def test_numbering_follows_first_appearance(self) -> None:
        """番号は最初に現れた順で振る (行を入れ替えなければ毎回同じ結果になる)。"""
        folded = fold_autogenerated_ids(f"{_B}\n{_A}\n{_B}\n")

        assert folded == "sem-#1\nsem-#2\nsem-#1\n"


class TestFoldingLeavesEverythingElseAlone:
    """畳むのは自動採番 id だけ。"""

    def test_hand_written_ids_are_untouched(self) -> None:
        """テストが手で置いた安定 id は畳まない (32 桁の 16 進ではないため)。"""
        text = "  entry_id: sem-existing\n  evidence_id: belief-evidence-e1\n"

        assert fold_autogenerated_ids(text) == text

    def test_episode_uuids_are_untouched(self) -> None:
        """episode_ids (uuid5) は内容から決まり毎回同じなので、畳まない。

        畳むと「内容が変わって id が変わった」ことが読めなくなる。実際
        c051a47a の表示変更はこの id の変化として現れた。
        """
        text = "  episode_ids: ['89b0cfdb-0adb-52ae-908f-b3c1deada88b']\n"

        assert fold_autogenerated_ids(text) == text

    def test_surrounding_text_is_preserved(self) -> None:
        """id の前後の文言は変えない。"""
        folded = fold_autogenerated_ids(f"  evidence_id: {_E}  <- 1 件目\n")

        assert folded == "  evidence_id: belief-evidence-#1  <- 1 件目\n"
