from enum import Enum

class InteractionEffectTypeEnum(Enum):
    GIVE_ITEM = "GIVE_ITEM"
    REMOVE_ITEM = "REMOVE_ITEM"
    CHANGE_OBJECT_STATE = "CHANGE_OBJECT_STATE"
    CHANGE_CONNECTION_STATE = "CHANGE_CONNECTION_STATE"
    REVEAL_OBJECT = "REVEAL_OBJECT"
    REVEAL_SUB_LOCATION = "REVEAL_SUB_LOCATION"
    SET_FLAG = "SET_FLAG"
    SHOW_MESSAGE = "SHOW_MESSAGE"
