"""LLM 向け表示・記憶層の契約"""

from ai_rpg_world.application.llm.contracts.dtos import (
    ActionResultEntry,
    EpisodeMemoryEntry,
    LlmCommandResultDto,
    LongTermFactEntry,
    MemoryLawEntry,
    MemoryRetrievalQueryDto,
    SystemPromptPlayerInfoDto,
    ToolDefinitionDto,
)
from ai_rpg_world.application.llm.contracts.interfaces import (
    IActionResultStore,
    IAvailabilityResolver,
    IAvailableToolsProvider,
    IContextFormatStrategy,
    ICurrentStateFormatter,
    IEpisodeMemoryStore,
    IGameToolRegistry,
    IMemoryExtractor,
    ILLMClient,
    ILLMPlayerResolver,
    ILlmTurnTrigger,
    ILongTermMemoryStore,
    IPredictiveMemoryRetriever,
    IPromptBuilder,
    IRecentEventsFormatter,
    IReflectionService,
    ISlidingWindowMemory,
    ISystemPromptBuilder,
)

__all__ = [
    "ActionResultEntry",
    "EpisodeMemoryEntry",
    "LlmCommandResultDto",
    "LongTermFactEntry",
    "MemoryLawEntry",
    "MemoryRetrievalQueryDto",
    "SystemPromptPlayerInfoDto",
    "ToolDefinitionDto",
    "IActionResultStore",
    "IAvailabilityResolver",
    "IAvailableToolsProvider",
    "IContextFormatStrategy",
    "ICurrentStateFormatter",
    "IEpisodeMemoryStore",
    "IGameToolRegistry",
    "IMemoryExtractor",
    "ILLMClient",
    "ILLMPlayerResolver",
    "ILlmTurnTrigger",
    "ILongTermMemoryStore",
    "IPredictiveMemoryRetriever",
    "IPromptBuilder",
    "IRecentEventsFormatter",
    "IReflectionService",
    "ISlidingWindowMemory",
    "ISystemPromptBuilder",
]
